environment: {}
parameters: {}
packages:
  - name: rooms
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: create
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: {}
        environment: {
          DATABASE_URL: "$DATABASE_URL"
        }
        annotations: {}
        limits: {}
